# Generated by Django 2.2.13 on 2020-08-28 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImgUrl', models.CharField(max_length=100, verbose_name='大图片路径')),
                ('ImgDesc', models.CharField(max_length=100, verbose_name='小图片路径')),
            ],
            options={
                'verbose_name': '图片表',
                'verbose_name_plural': '图片表',
                'db_table': 'ImageInfo',
            },
        ),
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '类别表',
                'verbose_name_plural': '类别表',
                'db_table': 'ProductsCategory',
            },
        ),
        migrations.CreateModel(
            name='CommodityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.ImageInfo')),
                ('ProductsCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.ProductsCategory')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
                'db_table': 'CommodityInfo',
            },
        ),
    ]
