# Generated by Django 2.2.13 on 2020-08-21 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_visit_time', models.DateTimeField(auto_now=True, verbose_name='最后访问时间')),
            ],
            options={
                'db_table': 'UserAccount',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(default=0, verbose_name='性别')),
                ('realname', models.CharField(max_length=40, verbose_name='真实姓名')),
                ('wechat', models.CharField(max_length=40, verbose_name='微信号')),
                ('email', models.CharField(max_length=40, verbose_name='邮箱')),
                ('nickname', models.CharField(max_length=40, verbose_name='昵称')),
                ('mobile', models.IntegerField(verbose_name='手机号')),
                ('birthdate', models.CharField(max_length=40, verbose_name='出生日期')),
                ('address', models.CharField(max_length=80, verbose_name='收货地址')),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.UserAccount')),
            ],
            options={
                'db_table': 'UserDetails',
            },
        ),
    ]
