# Generated by Django 2.2.13 on 2020-08-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraccount',
            table='useraccount',
        ),
        migrations.AlterModelTable(
            name='userdetails',
            table='userdetails',
        ),
    ]
