# Generated by Django 2.2.13 on 2020-08-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200820_0911'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraccount',
            table='UserAccount',
        ),
        migrations.AlterModelTable(
            name='userdetails',
            table='UserDetails',
        ),
    ]
