# Generated by Django 2.2.13 on 2020-08-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200820_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='nickname',
        ),
    ]
