# Generated by Django 2.2.13 on 2020-08-28 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodity', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='商品数量')),
                ('commoditysid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.CommodityInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserAccount')),
            ],
            options={
                'verbose_name': '购物车列表',
                'verbose_name_plural': '购物车列表',
                'db_table': 'cart',
            },
        ),
    ]
